name: pr-labeler

on: [pull_request]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: coverwallet/pr-labeler@feature/op-554-create-labels-if-not-exits
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}